/* eslint-disable @typescript-eslint/no-explicit-any */
import { Types } from "mongoose";

/**
 * @interface IPaymentTransaction
 * @description Interface representing a payment transaction in the system
 * Stores details of all payment operations with SSL Commerz
 */
export interface IPaymentTransaction {
  _id?: Types.ObjectId;
  /**
   * User ID who initiated the payment
   */
  userId: Types.ObjectId;
  /**
   * Optional Ride ID associated with this payment
   */
  rideId?: Types.ObjectId;
  /**
   * Unique transaction ID generated by the system
   */
  transactionId: string;
  /**
   * Payment amount in the specified currency
   */
  amount: number;
  /**
   * Currency code (e.g., 'BDT', 'USD')
   */
  currency: string;
  /**
   * Current status of the payment transaction
   * INITIATED: Payment process started
   * PENDING: Awaiting SSL Commerz response
   * COMPLETED: Payment successfully processed
   * FAILED: Payment processing failed
   * CANCELLED: User cancelled the payment
   * REFUNDED: Payment refunded
   */
  status:
    | "INITIATED"
    | "PENDING"
    | "COMPLETED"
    | "FAILED"
    | "CANCELLED"
    | "REFUNDED";
  /**
   * SSL Commerz transaction ID from their system
   */
  sslTransactionId?: string;
  /**
   * Payment method used (e.g., 'CARD', 'BKASH', 'NAGAD', 'ROCKET')
   */
  paymentMethod?: string;
  /**
   * Reason for payment (e.g., 'RIDE_FARE', 'WALLET_TOPUP')
   */
  description?: string;
  /**
   * Customer email address for payment
   */
  customerEmail: string;
  /**
   * Customer phone number for payment
   */
  customerPhone: string;
  /**
   * Customer name for payment
   */
  customerName: string;
  /**
   * Error message if payment failed
   */
  errorMessage?: string;
  /**
   * Response data from SSL Commerz API
   */
  sslResponse?: Record<string, any>;
  /**
   * Payment gateway response data
   */
  gatewayResponse?: Record<string, any>;
  /**
   * Timestamp when transaction was created
   */
  createdAt?: Date;
  /**
   * Timestamp when transaction was last updated
   */
  updatedAt?: Date;
  /**
   * Soft delete flag
   */
  isDeleted?: boolean;
}

/**
 * @interface ISSLCommerz
 * @description Interface for SSL Commerz payment request/response data
 */
export interface ISSLCommerz {
  store_id: string;
  store_passwd: string;
  total_amount: number;
  currency: string;
  tran_id: string;
  success_url: string;
  fail_url: string;
  cancel_url: string;
  ipn_url: string;
  cus_name: string;
  cus_email: string;
  cus_phone: string;
  cus_add1?: string;
  cus_city?: string;
  cus_country?: string;
  shipping_method?: string;
  product_name?: string;
  product_category?: string;
  product_profile?: string;
  value_a?: string;
  value_b?: string;
  value_c?: string;
  value_d?: string;
}

/**
 * @interface ISSLCommerzResponse
 * @description Interface for SSL Commerz IPN (Instant Payment Notification) response
 */
export interface ISSLCommerzResponse {
  tran_id: string;
  status: string;
  amount: string;
  currency: string;
  store_amount: string;
  store_id: string;
  card_type?: string;
  card_no?: string;
  card_issuer?: string;
  card_issuer_code?: string;
  card_brand?: string;
  risk_level?: string;
  risk_title?: string;
  base_fair?: string;
  value_a?: string;
  value_b?: string;
  value_c?: string;
  value_d?: string;
  transaction_details?: string;
  error_code?: string;
  error_message?: string;
  val_id?: string;
  APIConnect?: string;
  APIVersion?: string;
  ContentType?: string;
  ChargeAmount?: string;
  fee?: string;
  InsCard?: string;
  PaymentMethod?: string;
  GatewayTransID?: string;
}

/**
 * @interface IInitiatePaymentRequest
 * @description Interface for initiating a payment request
 */
export interface IInitiatePaymentRequest {
  userId: Types.ObjectId;
  rideId?: Types.ObjectId;
  amount: number;
  currency?: string;
  customerEmail: string;
  customerPhone: string;
  customerName: string;
  description?: string;
}

/**
 * @interface IPaymentValidationRequest
 * @description Interface for validating payment with SSL Commerz
 */
export interface IPaymentValidationRequest {
  val_id: string;
  amount: number;
  currency: string;
}
