import { Schema, model } from "mongoose";
import { IPaymentTransaction } from "./payment.interface";

/**
 * @schema PaymentTransactionSchema
 * @description MongoDB schema for storing payment transaction records
 * Tracks all payment operations and their current status
 */
const PaymentTransactionSchema = new Schema<IPaymentTransaction>(
  {
    /**
     * Reference to the User model
     */
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: [true, "User ID is required"],
    },
    /**
     * Optional reference to the Ride model
     */
    rideId: {
      type: Schema.Types.ObjectId,
      ref: "Ride",
    },
    /**
     * Unique transaction ID generated by the system
     * Format: TXN_TIMESTAMP_RANDOM
     */
    transactionId: {
      type: String,
      required: [true, "Transaction ID is required"],
      unique: true,
      index: true,
    },
    /**
     * Payment amount (in smallest unit, e.g., paisa for BDT)
     */
    amount: {
      type: Number,
      required: [true, "Payment amount is required"],
      min: [0, "Amount must be greater than or equal to 0"],
    },
    /**
     * Currency code (ISO 4217)
     */
    currency: {
      type: String,
      required: true,
      default: "BDT",
      enum: ["BDT", "USD", "EUR", "GBP"],
    },
    /**
     * Payment transaction status
     */
    status: {
      type: String,
      enum: [
        "INITIATED",
        "PENDING",
        "COMPLETED",
        "FAILED",
        "CANCELLED",
        "REFUNDED",
      ],
      default: "INITIATED",
      index: true,
    },
    /**
     * Transaction ID returned by SSL Commerz
     */
    sslTransactionId: {
      type: String,
      index: true,
    },
    /**
     * Payment method used (bank, mobile banking, etc.)
     */
    paymentMethod: {
      type: String,
      enum: ["CARD", "BKASH", "NAGAD", "ROCKET", "OTHER"],
    },
    /**
     * Description of the payment purpose
     */
    description: {
      type: String,
    },
    /**
     * Customer email for payment notification
     */
    customerEmail: {
      type: String,
      required: [true, "Customer email is required"],
      lowercase: true,
    },
    /**
     * Customer phone number
     */
    customerPhone: {
      type: String,
      required: [true, "Customer phone is required"],
    },
    /**
     * Customer name
     */
    customerName: {
      type: String,
      required: [true, "Customer name is required"],
    },
    /**
     * Error message if transaction failed
     */
    errorMessage: {
      type: String,
    },
    /**
     * Complete response object from SSL Commerz API
     */
    sslResponse: {
      type: Schema.Types.Mixed,
    },
    /**
     * Gateway response data
     */
    gatewayResponse: {
      type: Schema.Types.Mixed,
    },
    /**
     * Soft delete flag for data integrity
     */
    isDeleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    /**
     * Enable automatic timestamps (createdAt, updatedAt)
     */
    timestamps: true,
  }
);

/**
 * Create and export PaymentTransaction model
 */
export const PaymentTransaction = model<IPaymentTransaction>(
  "PaymentTransaction",
  PaymentTransactionSchema
);
